BITS_PER_COLOR = 2
PIXEL_SIZE_BITS = 3

PIXEL_SIZE = 1<<PIXEL_SIZE_BITS
VIDEO_HEIGHT = 720
VIDEO_WIDTH = 1280
FPS = 2
BOTTOM_BUFFER = 0  # set to 22 if want to avoid errors when Zoom HUD shows up
AVIDEO_HEIGHT = VIDEO_HEIGHT-(2+BOTTOM_BUFFER)*PIXEL_SIZE
AVIDEO_WIDTH = VIDEO_WIDTH-2*PIXEL_SIZE
PWIDTH = AVIDEO_WIDTH//PIXEL_SIZE
PHEIGHT = AVIDEO_HEIGHT//PIXEL_SIZE
NPIXELS = PWIDTH*PHEIGHT
BITS_PER_FRAME = NPIXELS*3*BITS_PER_COLOR
MAX_SIZE = BITS_PER_FRAME // 8
COLORWIDTH = 256 // (1<<BITS_PER_COLOR)
HEADER_SEPARATOR = b"+"
CLIENT_LISTEN_SOCK_PORT = 28888
CLIENT_LISTEN_SOCK_IP = "0.0.0.0"

SOCKS_SERVER_IP = "10.42.42.10"
SOCKS_SERVER_PORT = 1080
UPSTREAM_TIMEOUT = 3

